# Generated by Django 3.2.23 on 2024-01-30 16:15

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='mapper.find')),
            ],
        ),
    ]
