# Generated by Django 3.2.23 on 2024-01-30 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20240130_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='find',
        ),
        migrations.AddField(
            model_name='find',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapper.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
