# Generated by Django 3.2.23 on 2024-01-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20240130_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapper.location'),
        ),
    ]
