# Generated by Django 3.2.23 on 2024-01-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_alter_find_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.location'),
        ),
    ]
