# Generated by Django 3.2.23 on 2024-02-01 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_alter_find_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='find',
            name='suspected_edible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='find',
            name='suspected_poisonous',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='find',
            name='location',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AddField(
            model_name='find',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.habitat', blank=True),
            preserve_default=False,
        ),
    ]
