# Generated by Django 3.2.23 on 2024-02-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0006_auto_20240201_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_habitat', to='mapper.habitat'),
        ),
    ]
