# Generated by Django 3.2.23 on 2024-02-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_alter_find_habitat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitat',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='habitat',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
