# Generated by Django 3.2.23 on 2024-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0009_auto_20240201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='suspected_edible',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='find',
            name='suspected_poisonous',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
