# Generated by Django 3.2.23 on 2024-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0010_auto_20240201_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='location_coordinates',
            field=models.CharField(blank=True, default=1, max_length=50),
        ),
    ]
