# Generated by Django 3.2.23 on 2024-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0011_find_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='location_coordinates',
            field=models.TextField(),
        ),
    ]
