# Generated by Django 3.2.23 on 2024-02-02 14:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0012_alter_find_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='find',
            name='location',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20),
        ),
    ]
