# Generated by Django 3.2.23 on 2024-02-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0016_auto_20240212_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='find',
            name='location',
        ),
    ]
